In [36]:
import tensorflow as tf

In [37]:
import numpy as np

In [38]:
xy = np.loadtxt('trainText.txt', unpack=True, dtype='float32')

In [39]:
x_data = xy[0:-1]
y_data = xy[-1]
print x_data, y_data

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  3.  0.  5.]
 [ 0.  2.  0.  4.  0.]] [ 1.  2.  3.  4.  5.]


In [40]:
W = tf.Variable(tf.random_uniform([1, len(x_data)], -1, 1))
b = tf.Variable(tf.random_uniform([1], -1, 1))

In [41]:
hypothesis = tf.matmul(W, x_data)

cost = tf.reduce_mean(tf.square(hypothesis - y_data))

In [42]:
a = tf.Variable(0.1) # learning rate, alpha
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost) # minimize cost

In [43]:
init = tf.initialize_all_variables()

In [44]:
sess = tf.Session()
sess.run(init)

In [45]:
for step in xrange(2001):
    sess.run(train)
    if step % 20 == 0:
        print step, sess.run(cost), sess.run(W)

0 0.376551 [[ 0.93102717  0.83086365  0.5036459 ]]
20 0.0483824 [[ 0.5214451   0.86292684  0.83736372]]
40 0.0140087 [[ 0.28058475  0.92624211  0.91248691]]
60 0.00405611 [[ 0.15098006  0.96031159  0.95291001]]
80 0.00117441 [[ 0.08124098  0.97864401  0.97466135]]
100 0.000340043 [[ 0.04371502  0.98850852  0.98636544]]
120 9.84553e-05 [[ 0.02352266  0.99381655  0.99266338]]
140 2.85077e-05 [[ 0.01265734  0.99667275  0.99605227]]
160 8.2543e-06 [[ 0.00681076  0.9982096   0.99787575]]
180 2.38977e-06 [[ 0.0036648   0.99903655  0.99885696]]
200 6.91977e-07 [[ 0.00197203  0.99948168  0.99938494]]
220 2.00414e-07 [[ 0.00106116  0.99972117  0.99966902]]
240 5.80143e-08 [[  5.70995267e-04   9.99849975e-01   9.99821901e-01]]
260 1.68069e-08 [[  3.07232811e-04   9.99919176e-01   9.99904215e-01]]
280 4.862e-09 [[  1.65368940e-04   9.99956489e-01   9.99948382e-01]]
300 1.40484e-09 [[  8.89557632e-05   9.99976635e-01   9.99972224e-01]]
320 4.09307e-10 [[  4.79144037e-05   9.99987602e-01   9.999850