In [13]:
import tensorflow as tf
import numpy as np

In [14]:
xy = np.loadtxt('TrainText03.txt', unpack=True, dtype='float32')

In [15]:
x_data = np.transpose(xy[0:3])
y_data = np.transpose(xy[3:])

In [16]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.zeros([3, 3]))

In [17]:
hypothesis = tf.nn.softmax(tf.matmul(X, W))

In [18]:
learning_rate = 0.01 # Alpha

In [19]:
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypothesis), reduction_indices=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

In [20]:
init = tf.initialize_all_variables()

In [21]:
#______________learning process
with tf.Session() as sess:
    sess.run(init)
    
    for step in xrange(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print step, sess.run(cost, feed_dict={X: x_data, Y: y_data}), sess.run(W)
            
#______________Testing parts
    
    #arg_max() - used for 'one-hot' encoding
            
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7]]})
    print "a :", a, sess.run(tf.arg_max(a, 1))
    
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4]]})
    print "b :", b, sess.run(tf.arg_max(b, 1))
    
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0]]})
    print "c :", c, sess.run(tf.arg_max(c, 1))

0 1.09048 [[-0.00083333  0.00041667  0.00041667]
 [ 0.00166667  0.00291667 -0.00458333]
 [ 0.00166667  0.00416667 -0.00583333]]
200 0.985653 [[-0.21679303 -0.05050437  0.26729742]
 [ 0.02901031 -0.06265054  0.03364029]
 [ 0.04244109  0.12451769 -0.16695869]]
400 0.926073 [[-0.41495511 -0.10318027  0.51813519]
 [ 0.03762176 -0.10302337  0.06540174]
 [ 0.07457665  0.17761268 -0.25218898]]
600 0.879342 [[-0.59596533 -0.1515553   0.74752003]
 [ 0.04480708 -0.11983915  0.07503238]
 [ 0.10447746  0.20644082 -0.31091776]]
800 0.840971 [[-0.76270223 -0.19499816  0.95770001]
 [ 0.05223157 -0.12450957  0.07227841]
 [ 0.13095778  0.22218271 -0.35314   ]]
1000 0.808647 [[-0.91752577 -0.2334879   1.15101326]
 [ 0.06007884 -0.12292791  0.06284945]
 [ 0.15438823  0.23068959 -0.38507724]]
1200 0.780959 [[-1.06231129 -0.26727253  1.32958329]
 [ 0.06808005 -0.11823834  0.05015875]
 [ 0.17550454  0.23514733 -0.41065112]]
1400 0.756943 [[-1.19854808 -0.29670808  1.49525583]
 [ 0.07591439 -0.11214777  0.03